### ISSUE TITLE
Build isoscape over short periods of time

### ISSUE THREAD

**Issue by PatWright** [courtiol/IsoriX#109]
Hi,

I'm trying to build two isoscapes in Europe based on Spring 2015 and Autumn 2015 data (when samples were collected) from GNIP. After filtering all the data I end up with about 30 points that don't cover my study area and quite weak models. Do you have any suggestions to improve my isoscapes?

Thanks,
Patrick

**Comment by stephkramer** [comment]
Dear Patrick,

the variance in the GNIP data for these two months may be extremely high (not sure where across Europe you sample, but when it is in areas with high precipitation during these months this can happen); also, you might have too few data points per location. I suggest you build an isoscape across many years (and months).

Best wishes
Stephanie

Von: PatWright [mailto:notifications@github.com]
Gesendet: Mittwoch, 24. Oktober 2018 12:48
An: courtiol/IsoriX
Cc: Subscribed
Betreff: [courtiol/IsoriX] Build isoscape over short periods of time (#109)


Hi,

I'm trying to build two isoscapes in Europe based on Spring 2015 and Autumn 2015 data (when samples were collected) from GNIP. After filtering all the data I end up with about 30 points that don't cover my study area and quite weak models. Do you have any suggestions to improve my isoscapes?

Thanks,
Patrick

**Comment by PatWright** [comment]
Hi Stephanie, 

Thanks for your reply. I'll just try more years (2013 to 2017 to start) and that should hopefully solve  my problem. 

Best wishes,
Patrick

**Comment by courtiol** [comment]
In general, building isoscape using only the data from some months has been shown to be problematic because the ground water does not often just reflect the isotopic signature of present time only but it is influenced by precipitations over several months before... They have been several papers on that which I could dig out if you don't find them.
++
