### ISSUE TITLE
Error in isoscape function?

### ISSUE THREAD

**Issue by LaraSp** [courtiol/IsoriX#112]
Hi!

When I'm trying to run `EuropeScape <- isoscape(raster = ElevRaster, isofit = EuropeFit)`  I got this error and warning message: 

> Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In isoscape(raster = ElevRaster, isofit = EuropeFit) :
  The isofit has been fitted on a different version of spaMM than the one called by IsoriX. This may create troubles in paradize...
Timing stopped at: 0.49 0.04 0.9"

It worked perfectly  last week. I've updated spaMM package and Isorix as well and I still got the same message. Any ideas how i can fix it?

Many thanks

**Comment by f-rousset** [comment]
Hi,

> The isofit has been fitted on a different version of spaMM
and
>  I've updated spaMM package... and I still got the same message
may mean exactly what the message means: "isofit has been fitted on a different version of spaMM" and updating spaMM does not mean that the isofit has been refitted with the new spaMM version.

You can check the version of spaMM which produced `EuropeFit` by `how(EuropeFit)`.

Best,
 
F.

**Comment by courtiol** [comment]
Dear @LaraSp,
I think that you must have saved your fitted model somewhere, in a `EuropeFit.rda` object perhaps.
That object seems to have been created before you updated `spaMM`.
So what you should simply do is to refit the model and save it again if needed.
Does that solve the issue?
Best,
Alex
