### ISSUE TITLE
Function to create empty grids with coordinates

### ISSUE THREAD

**Issue by courtiol** [courtiol/IsoriX#141]
When people do not need to use elevation/depth, it is a little silly to make them use a elevation/depth raster.
What we need is a simple function creating the grid.

**Comment by courtiol** [comment]
Kind of, but with coordinates spanning specific lat/long at regular interval.
It is not difficult to code the function, but the question is more what kind of input we want the user to use.
I guess `lat_min`, `lat_max`, `long_min`, `long_max` and `n_cell` would be good.
Then we just need to use `n_cell` as a basis to define the sequences of lat and long.
So `n_cell` would be an approximate number of cells.
I think that would meet the task, what do you think?

**Comment by stephkramer** [comment]
Yes, with the slight addition that I would separate this into nrows() and ncols(), because n_cells is very abstract for users, as it is the product. But often one knows the dimensions.

**Comment by courtiol** [comment]
I was thinking that one knows more how many cells they want on a grid that the number in x and y.
With `n_cell` I could make sure that both lat and long are at same resolution, with numbers of rows and columns that could lead to very different lat or long resolution which may look weird.
Perhaps I will provide both options then.
