### ISSUE TITLE
change authors in description using new format

### ISSUE THREAD

**Issue by courtiol** [courtiol/IsoriX#87]
There is a better way of writing authors in the DESCRIPTION file that allows for the recognition of ORCID numbers. Check dplyr package for example. We should implement that.

**Comment by stephkramer** [comment]
will do!

Alexandre Courtiol <notifications@github.com> schrieb am Do., 14. Juni
2018, 18:14:

**Comment by courtiol** [comment]
Up to you, I could also do it, it would take me 10 sec but I wrote a note here because I did not want to do it right now... If you do, use the model I used for my package BeginR, which is a bit more polished than the one form dplyr. ++

**Comment by f-rousset** [comment]
Hi...
Accordingly, I am 
person("François", "Rousset", role = "aut",
                     comment = c(ORCID = "0000-0003-4670-0371"))
F.

**Comment by courtiol** [comment]
done
